### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Loosed dependencies a little. Also, the stable flag isn't needed, because it is on by default anyway.

### CODE REVIEW

**Comment by jasonlewis** [comment]
Hm, what's the benefit here of loosening the dependencies?

**Comment by GrahamCampbell** [comment]
You are forcing me to use symfony 2.4, but what if I want to use 2.5... I can't. That's the important change.

The changed to require-dev just mean we can get the newest phpunit whenever it comes out in stable, and my change to mockery really makes no difference. My change to predis is quite trivial too.

**Comment by jasonlewis** [comment]
No worries sounds good. Just clarifying.

**Comment by GrahamCampbell** [comment]
Thanks for your work on this repo. It's really awesome!

**Pull request merged**
