### PR TITLE
Read access token from basic auth http

### PR DESCRIPTION
**Pull request by joecohens**
Feature to read from basic auth http

curl http://example.com  \
   -u <token>:

### CODE REVIEW

**Comment by jasonlewis** [comment]
Is this a part of the spec? I couldn't locate it. Cheers mate.

**Comment by joecohens** [comment]
Sorry mate! I didn't follow the spec, I thought it was a nice feature. I'll close this now.

Nice work! ;)

**Comment by jasonlewis** [comment]
Yeah you should be sending the access token through the authorization
header. Cheers mate. Not really production ready but getting there.

**Comment by joecohens** [comment]
I like the code is very clean! Do you have any roadmap or todos, so I can help you?

**Pull request closed without merging**
